### ISSUE TITLE
tracking.services.mozilla.com

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#3263]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

tracking.services.mozilla.com

### Why should the domain(s) be unblocked?

False positive, actually used for Firefox's tracking protection. Can be seen ex. [here](https://wiki.mozilla.org/Services/TrackingProtection/Shavar_Server_-_Testing):

`$ curl -d" "  '[https://tracking.services.mozilla.com/list?client=foo&appver=1&pver=2.2'](https://tracking.services.mozilla.com/list?client=foo&appver=1&pver=2.2%27)`

### Privacy

- [X] I confirm that the report does not contain any private information.
