### ISSUE TITLE
*.ceph.com tracker.ceph.com

### ISSUE THREAD

**Issue by 4d62** [hagezi/dns-blocklists#3286]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

*.ceph.com
tracker.ceph.com

### Why should the domain(s) be unblocked?

bug tracker for the ceph project https://www.ceph.com/en/ https://github.com/ceph/ceph?tab=readme-ov-file#reporting-issues

### Privacy

- [X] I confirm that the report does not contain any private information.
