### ISSUE TITLE
TODO: Samsung native tracker list

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#3814]
https://arxiv.org/pdf/2409.06203

**Samsung native tracker list**

- [x] Determine tracking domains
- [x] Compile list
- [x] Integrate into the build system
- [x] Provide native version
- [x] Integrate into normal Lists
- [x] Provide updated lists
