### ISSUE TITLE
blocking tracking.swap.fm breaks certain podcasts

### ISSUE THREAD

**Issue by pokegamer5547** [hagezi/dns-blocklists#3820]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

tracking.swap.fm

### Why should the domain(s) be unblocked?

Some podcasts i encountered, like this one uses tracking.swap.fm within the rss feed's media:content url tag of the podcast episode which breaks the playback. Example is this link
`https://chtbl.com/track/39E17/podtrac.com/pts/redirect.mp3/pscrb.fm/rss/p/pdrl.fm/057e02/tracking.swap.fm/track/SxlTEPDY7xDg35RXkASs/traffic.omny.fm/d/clips/e73c998e-6e60-432f-8610-ae210140c5b1/96c5c41e-0bc8-4661-b184-ae32006cd726/8226a42b-bbf7-4eef-a915-b1e900aa7838/audio.mp3?utm_source=Podcast&amp;in_playlist=d623ef0b-3fee-4c26-b815-ae32006cd739`
It redirects before getting to final destination, and tracking.swap.fm is blocked so it can't proceed from there. Idk whether we should really unblock it or not since it is a tracking domain. But it does breaks stuff. 

### Privacy

- [X] I confirm that the report does not contain any private information.
