### ISSUE TITLE
Unblock track-and-trace.cxc.arvato-scs.digital, used for order tracking

### ISSUE THREAD

**Issue by mahtd** [hagezi/dns-blocklists#4434]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

track-and-trace.cxc.arvato-scs.digital

### Why should the domain(s) be unblocked?

Used for tracking the shipment of orders. On `https://www.hellolingo.com/orders/tracking/[ORDER UUID]`, it makes a call to `https://track-and-trace.cxc.arvato-scs.digital/v2/C100107/order/[ORDER NUMBER]?recipientZipcode=[ZIPCODE]`, which responds with the shipment information

I can share the URL of the actual page with you privately if needed

### Privacy

- [X] I confirm that the report does not contain any private information.
