### ISSUE TITLE
Allow tracking.feedpress.com

### ISSUE THREAD

**Issue by NeonHunter82** [hagezi/dns-blocklists#4445]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi PRO++ mini, Multi ULTIMATE, Multi ULTIMATE mini

### Which domain(s) should be unblocked?

Only `tracking.feedpress.com`.

### Why should the domain(s) be unblocked?

Breaks listening to Jupiter Broadcasting's shows via their all shows feed.

#### Screenshot
![Screenshot_20241127-190805](https://github.com/user-attachments/assets/1eb0e5cb-9236-431e-aad0-0e87e438f317)

### Privacy

- [X] I confirm that the report does not contain any private information.
