### ISSUE TITLE
tracker.greatposterwall.com

### ISSUE THREAD

**Issue by NLZ** [hagezi/dns-blocklists#4540]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi PRO++ mini

### Which domain(s) should be unblocked?

tracker.greatposterwall.com

### Why should the domain(s) be unblocked?

It's a torrent tracker

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by NLZ** [comment]
Plus `tracker.hdarea.club`, `tracker.m-team.io` and probably other chinese torrent trackers. Not sure what your source is for them, but it might be poisoned.
